name: unitana
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/cities_v1.json
    - assets/brand/unitana_logo.png
    - assets/fonts/

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-ExtraBold.ttf
          weight: 800
